{
  "data-path": "/data/share/input/train_text_document",
  "vocab-file": "/data/tokenizer/del_post_processor_tokenizer.json",
  #"tokenizer_type": "HFTokenizer",
  "save": "checkpoints",
  "load": "checkpoints",
  "checkpoint_validation_with_forward_pass": False,
  "tensorboard-dir": "tensorboard",
  "log-dir": "logs",
  "use_wandb": False,
  "wandb_host": "https://api.wandb.ai",
  "wandb_project": "gpt-neox"
}
